### ISSUE TITLE
Fix R symbols/names -> clojure symbols/keywords conversion

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clojuress#13]
We have two places where R symbol conversion is applied.

1. Named list keys are converted to keywords
2. R library symbols are converted to Clojure symbols.

Both keys and symbols can be invalid in various ways in Clojure so proper conversion should be made.

Strategy is:

1. Convert invalid names (keys) to a string
2. Skip invalid symbols (like `"[[<-.factor"`) or wrap into dedicated function (like `brabra`)

For both cases we use `#"[\Q[](){}#@;:,\/`^'~\"\E].*"` which catches only first letter as forbidden letter.

Two regexes should be prepared for each cases separately and tested against real names taken from R libraries (mainly `base`).

**Comment by daslu** [comment]
Related discussion:

https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/names

https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/access.20to.20dataframes

**Comment by genmeblog** [comment]
I think it should be still open since it doesn't catch different cases like this:

```clojure
(->> "list(A=1,B=2,'123#strange<text> ()'=3)"
     r
     r->clj)
;; => {:A [1.0], :B [2.0], :123#strange<text> () [3.0]}
```
