### ISSUE TITLE
Create `defr`

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clojuress#24]
Create `defr` or `def-r` which creates a symbol on the R side too.

See discussion: https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/formulas

**Comment by genmeblog** [comment]
I think it's not necessary. You can safely do `(def myval (r.base/<- 'myval ...)`

**Comment by daslu** [comment]
Sounds good.

**Comment by genmeblog** [comment]
Closing, since it's not necessary.
