### ISSUE TITLE
Memory management issues

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clojuress#25]
`using-sessions/eval-code`  sets garbage collector for RObject. It seems not to work properly. Objects created by `require-r` and bound to vars are set to NULL very quickly. They are no longer available.

Discussion: https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/releasing.20memory

**Comment by daslu** [comment]
Fixed it by loading the Renjin Jar on-the-fly, if and when necessary, using alembic.

**Comment by daslu** [comment]
Commented about this issue by mistake. It is not yet solved in `BETA5`.

**Comment by genmeblog** [comment]
1.0.0-BETA8-SNAPSHOT
