### ISSUE TITLE
Loading dynamic dependencies fails with Java 11. The problem may be related to Alembic.

### ISSUE THREAD

**Issue by daslu** [scicloj/clojuress#31]
We get this error message:
```
Syntax error (ExceptionInfo) compiling at (alembic/still.clj:65:1).
Alembic can not manipulate specified ClassLoader.
```
when trying to add a dependency on runtime here:
https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/renjin.clj#L5

Discussion and possible solution by @joinr:
https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/problems.20with.20alembic

**Comment by genmeblog** [comment]
Change to `pomegranade` solves the issue
