### ISSUE TITLE
Simpler behaviour of code generation with simple values

### ISSUE THREAD

**Issue by daslu** [scicloj/clojuress#37]
Currently, the `->code` function for code generation converts almost all Clojure values (except for symbols and functions) to corresponding RObjects, and puts these objects' temporary names in the generated code.

See the

E.g.:
```clojure
(r/->code 3.14)
;; => ".MEM$xf63d99caf6de4aa1"
(r/->code false)
;; => ".MEM$xc6df8e9af9d94817"
(r/->code [1 2 3])
;; => ".MEM$x55d70535c65c4328"
```

For simple primitive values, such as number, strings and booleans, we would rather put those values explicitly in the generated R code.

That is, what we want is this:
```clojure
(r/->code 3.14)
;; => "3.14"
(r/->code false)
;; => "FALSE"
(r/->code [1 2 3])
;; => ".MEM$x55d70535c65c4328"
```

This is will require a rather small change at the [codegen](https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/codegen.clj) namespace, and some adapdtation of the tests.

**Comment by genmeblog** [comment]
Prepared a branch `numbers`
Still testing and need to write tests in tutorial

```clojure
(r/->code 1)
;; => "1"
(r 1)
;; => [1] 1

(r/->code '(+ 1 2.1))
;; => "(1 + 2.1)"
(r '(+ 1 2.1))
;; => [1] 3.1

(r/->code 2/3)
;; => "(2/3)"
(r 2/3)
;; => [1] 0.66666667

(r/->code '(+ 1 2.0 3/4))
;; => "(1 + 2.0 + (3/4))"
(r '(+ 1 2.0 3/4))
;; => [1] 3.75

(r/->code true)
;; => "TRUE"
(r true)
;; => [1] TRUE

(r/->code (> 3 4))
;; => "FALSE"
(r (> 3 4))
;; => [1] FALSE
```

**Comment by genmeblog** [comment]
BETA9-SNAPSHOT
