### ISSUE TITLE
ensure locking when talking with an Rserve

### ISSUE THREAD

**Issue by daslu** [scicloj/clojuress#40]
In the main place we use it, we use a lock:
https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/impl/rserve/java.clj#L41

But there are some parts of the Session implementation that do not go through that entry point:
https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/impl/rserve/session.clj#L23

**Comment by daslu** [comment]
Related discussion:
https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/alternatives.20to.20Rserve/near/188821420

**Comment by genmeblog** [comment]
1.0.0-BETA8-SNAPSHOT
