### ISSUE TITLE
tech.ml.dataset do not recognize `NA` in logical columns

### ISSUE THREAD

**Issue by daslu** [scicloj/clojuress#50]
Rserve has a maximal socket buffer size, and that limits the amount of data we can pass through it.

Our solution can be to wrap the `r->clj` and `clj->r` functions in a way that will transparently break the data into chunks before passing it over the socket.

**Comment by genmeblog** [comment]
I'm pretty sure they can. The error referenced in [zulip discussion](https://clojurians.zulipchat.com/#narrow/stream/204621-r-interop/topic/fread.20problems.20with.20large.20datasets) is a result of improper translation of logical columns

**Comment by genmeblog** [comment]
My conclusion is that transfer big amount of data is possible and works. What doesn't work is conversion of logical types to tech.ml.dataset

**Comment by genmeblog** [comment]
Next release of tech.ml.dataset will cover this issue

**Comment by genmeblog** [comment]
It's fixed already in t.m.ds
