### ISSUE TITLE
column-map in tech.ml.dataset is renamed starting from beta39

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clojuress#64]
"Renamed column-map to column-name->column-map"

Be careful when upgrading to the newest tech.ml.dataset

**Comment by daslu** [comment]
Updated the deps versions, with the adaptation you suggested.
https://github.com/scicloj/clojisr/commit/6d320028b1222643e2351d5dda6cb6e7defd676e
All tests pass.

Deployed this to the `"BETA-11-SNAPSHOT"` [version](https://clojars.org/scicloj/clojisr/versions/1.0.0-BETA11-SNAPSHOT).

**Comment by daslu** [comment]
Closing this as this was fixed in `"BETA-11"`.
