### ISSUE TITLE
idea: watchdog for r process

### ISSUE THREAD

**Issue by awb99** [scicloj/clojuress#67]
I think killing off unwanted r processes is something that makes working with clojisr a little bit of a pain.

I guess this could be solved with a watchdog process that will be started whenever there is a new r engine that will be started, and it gets passed the operating process id of both clojure and R process. the watcher will kill r process whenever clojure process gets terminated.
This way if there is any unforeseen crash or strange clj termination, it is ensured that R gets killed.

It might be that jvm offers some eventhandler that can do some cleanup on exceptions; this could solve the issue also.

**Comment by genmeblog** [comment]
It's already done and watchdog is implemented. After JVM is closed, R project should be killed.

https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/r.clj#L183

Do you experience different behaviour?

**Comment by awb99** [comment]
Oh nice! I still was running an R process killer script all this time. As a few months ago I had the issue, that there were always R processes hanging around. Haven't had an issue. But could not tell if it works, because of my script. I have already deleted my script. In case I get R processes accumulating again, I will reopen.

**Comment by awb99** [comment]
This just happened now:

```
INFO: [:clojisr.v1.impl.rserve.proc/spawn {:process ("/usr/bin/R" "--no-save" "--no-restore-data" "--slave" "-e" "library(Rserve); run.Rserve(port=36197);")}]
Execution error (ConnectException) at java.net.PlainSocketImpl/socketConnect (PlainSocketImpl.java:-2).
Connection refused (Connection refused)

Full report at:
/tmp/clojure-13871480388467796455.edn
```
I guess the reason was one unclean shutdown. On the next restart of the app it worked all fine.

**Comment by genmeblog** [comment]
It's already issued: https://github.com/scicloj/clojisr/issues/62

I think this is not related to cleaning process. But who knows.

**Comment by genmeblog** [comment]
Closing, Socket issue is separate problem and is not related to R process (rather longer startup).
