### ISSUE TITLE
linter integration

### ISSUE THREAD

**Issue by awb99** [scicloj/clojuress#68]
I think sooner or later we will need a custom linter for clojisr. (see screenshot below).

Or what you might want to do is to generate a clojure namespace like lib python clj, which
essentially allows to require R namespaces that are wrapped into clojure namespaces. Then
you could at initialization time essentially build all the needed namespaces, and from there on
working with R namespaces will be identical to working with clj namespaces,

line 28: base is not recognised.

![linter defs](https://user-images.githubusercontent.com/10854682/83456545-8af0bf00-a425-11ea-8731-9bd1549c251f.png)

**Comment by genmeblog** [comment]
I have 600 packages in R (most of are dependencies), this requires generating huge amount of clojure code. I'm not sure if linter is possible in our case...

**Comment by awb99** [comment]
I added a linter config to clj kondo in clojisr-gorilla:
https://github.com/pink-gorilla/clojisr-gorilla/blob/master/.clj-kondo/config.edn

Unfortunately I was not successful in configuring away the R related errors.
I think it is mandatory for every project to run linters. Too many errors the linter
can fix; at least for me.

I don't want to add source code that has clojisr code to a folder that is exempt from linting.

Not an urgent problem. But if R code gets more and more intermingled with clj code,
then it should be resolved in some way...
