### ISSUE TITLE
plotting-speed

### ISSUE THREAD

**Issue by awb99** [scicloj/clojuress#70]
It seems the only way to get plots out from R is by saving to file. Now this might be a perfrmance bottomleg, as each  plot needs to hit the disk. I am wondering if we can define some device / filename that is pure in memory? Perhaps the jvm does this already. If it is on os level, then I guess it requires some onfiguration. There should be some option available...

**Comment by genmeblog** [comment]
Even though, how do you want to access R memory from JVM without transfering data to the Clojure?
I've spend certain amount of time on this and there is an option to gather RAW bitmap but I again transfering it through the socket will be way, way slower than just saving to the drive on the R side and reading back on Clojure side.

Also, there is something like JavaGD (https://cran.r-project.org/web/packages/JavaGD/index.html) but I haven't had an opportunity to fight with it so I don't know how does it work and if there is an option to connect to the existing JVM (it probably spawns its own)

**Comment by genmeblog** [comment]
As tested by Daniel here https://clojurians.zulipchat.com/#narrow/stream/224816-clojisr-dev/topic/understanding.20slow.20plotting `clojisr` rendering speed is almost the same as in R natively. Closing since it's nothing to do here.
