### ISSUE TITLE
Refer to clj-py-r-template from here

### ISSUE THREAD

**Issue by behrica** [scicloj/clojuress#74]
I setup a template (using clj-new), which creates a skeleton project including R and Docker having RServe installed.
This is in my view the quickest route  to use clojisr, given you have Docker.

https://github.com/behrica/clj-py-r-template

The Dockerfile of the template adds as well python + libpython-clj for completeness.

So it has in a single place all dependencies and they do work together and no further setup is required.
```
* R: 4.0.0
* RServe: latest from rforge.net
* python: 3.8.2
* java:  openjdk 11
* clojure: 1.10.1
* clj-python/libpython-clj 1.45
* scicloj/clojisr 1.0.0-BETA11
* cider-nrepl 0.25.2
```

Maybe you could refer to it from here in some form.

**Comment by genmeblog** [comment]
Lovely! I will update the README soon.

**Comment by genmeblog** [comment]
Readme updated. Please close the issue if you find it ok.
