### ISSUE TITLE
Cannot find Renjin 3.5-beta76 in 1.0.0-BETA15

### ISSUE THREAD

**Issue by joannecheng** [scicloj/clojuress#78]
When I try to start the repl using the latest version of Clojisr (1.0.0-BETA15) I get the following error message:

```
Error building classpath. Could not find artifact org.renjin:renjin-core:jar:3.5-beta76 in central (https://repo1.maven.org/maven2/)
```

Looking at Maven, it looks like 3.5-beta76 doesn't exist.

**Comment by genmeblog** [comment]
Please try latest SNAPSHOT. https://clojars.org/scicloj/clojisr/versions/1.0.0-BETA16-SNAPSHOT

We removed Renjin support since it's not complete and problematic.

**Comment by genmeblog** [comment]
Generally Renjin is not published on Maven. We've added it as a separate repository in project.clj/deps.edn. but it seems it's not enough. You have to copy url to your deps or use SNAPSHOT.

**Comment by joannecheng** [comment]
Awesome, thanks for that! Latest snapshot works for me! :100:

**Comment by behrica** [comment]
Can be closed, I suppose.
