### ISSUE TITLE
Add p_load as part of the usual workflow

### ISSUE THREAD

**Issue by daslu** [scicloj/clojuress#9]
[p_load](https://www.rdocumentation.org/packages/pacman/versions/0.5.1/topics/p_load) can install missing packages if they are missing.

Following a suggestion of Nick Stares, we may wish to make it an almost-transparent behaviour in our interop story.

Should it be part of the `require-r` default behaviour?

**Comment by behrica** [comment]
(automated) dependency management in R is very tricky, 
as packages might have native operating system library dependencies.

All R package management solutions just as pacman, renv, packrat, devtools, can at the end not solve this,
as it is not solvable from inside R.

The only solution for this is Docker.

In my view, we could / should promote the usage of docker for clojisr, and handle R dependencies in Docker.

**Comment by genmeblog** [comment]
I agree with the part that we can't solve various system deps for certain packages so I would leave it to the user.

Docker is the solution as well (however as a Windows 10 Home user it's still not available for me, unless 2004 update will come)

**Comment by genmeblog** [comment]
I would close it. Package management should be external to the library (user still can call `(r.base/install-packages [...])` from `clojisr`. The other solution is Docker as @behrica mentioned (and prepared a solution for that).

To be closed imho.

**Comment by genmeblog** [comment]
Can we close it?

**Comment by behrica** [comment]
Yes

genmeblog ***@***.***> schrieb am So., 14. Apr. 2024, 20:56:

**Comment by genmeblog** [comment]
Ok! Closed.
