### ISSUE TITLE
close integration with R package 'Require'

### ISSUE THREAD

**Issue by behrica** [scicloj/clojuress#90]
The r package [Require](https://cran.r-project.org/web/packages/Require/index.html) seems to be the closest
to declarative package management in R.

It would be nice, if `clojisr` could have a clojure function, to be used like:
```clojure
(require-r-packages ["data.table (==1.12.8)", "dplyr", "reproducible", 
          "PredictiveEcology/SpaDES@development", "raster (>=3.1.5)"]
```

and gets translated into a call to:

```R
Require(c("data.table (==1.12.8)", "dplyr", "reproducible", 
          "PredictiveEcology/SpaDES@development", "raster (>=3.1.5)"), 
        libPaths = tempdir(),
        standAlone = TRUE)
```        
These type of lines could be the first lines in a clj based notebook, which uses R later.

**Comment by behrica** [comment]
some syntactic sugar for doing

```clojure
(require '[clojisr.v1.r :refer [r require-r]])
(require-r '[Require])
(require-r '[base])
(r.Require/Require ["data.table (==1.12.8)"  
                               "dplyr" 
                                "reproducible"  
                                "PredictiveEcology/SpaDES@development"
                                 "raster (>=3.1.5)"] 
        :libPaths (r.base/tempdir) 
        :standAlone true)
```

**Comment by behrica** [comment]
or it could go to `noj` as opinionated support for `Require`

**Comment by genmeblog** [comment]
It can also go under `clojisr.v1.applications.require` namespace.

**Comment by behrica** [comment]
Maybe it is too opinionated to be in Clojisr.
R has at least 10 package managers all with pros and cons.

I am still dreaming about a perfect "declarative" package manager for R;
but I do accept that "native" dependencies are unmanageable across different OSS.

Personally I migrate to devcontainer, as there I can have a single file which specifies R packages incl. native dependencies.

**Comment by behrica** [comment]
Too opinionated to be here.
